-- Church catalog fields
ALTER TABLE churches ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE churches ADD COLUMN IF NOT EXISTS city VARCHAR(255);
ALTER TABLE churches ADD COLUMN IF NOT EXISTS state VARCHAR(100);
ALTER TABLE churches ADD COLUMN IF NOT EXISTS region VARCHAR(255);
ALTER TABLE churches ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION;
ALTER TABLE churches ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION;
ALTER TABLE churches ADD COLUMN IF NOT EXISTS whatsapp VARCHAR(30);
ALTER TABLE churches ADD COLUMN IF NOT EXISTS phone VARCHAR(30);
ALTER TABLE churches ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE churches ADD COLUMN IF NOT EXISTS cover_url TEXT;
ALTER TABLE churches ADD COLUMN IF NOT EXISTS photos JSONB DEFAULT '[]';

CREATE INDEX IF NOT EXISTS idx_churches_city ON churches(city);
CREATE INDEX IF NOT EXISTS idx_churches_state ON churches(state);
CREATE INDEX IF NOT EXISTS idx_churches_lat_lng ON churches(lat, lng);
